import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

function Car() {
  return <h2>Hi, I am a Car!</h2>;
}

// const root = ReactDOM.createRoot(document.getElementById("root"));
// root.render(<Car />);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
